### ISSUE TITLE
Small note

### ISSUE THREAD

**Issue by tlienart** [guberger/guberger.github.io#1]
Hello!

Not sure if you're still working on this but FYI looking at this it seems you started with Franklin < 0.6 and the "old" file system where everything would be put in the `pub` folder. While this was supported for a while, it's now being deprecated and I'd suggest moving over to the "new" way where things get published in a `__site/` folder. 

Moving from one to the other is pretty straightforward, see instructions here: https://github.com/tlienart/Franklin.jl/blob/master/NEWS.md#v06-1 

If you need some help with this don't hesitate to ping me.

Cheers

**Comment by tlienart** [comment]
aah t'es d'ICTEAM 👋

**Comment by guberger** [comment]
Salut! En effet :-) J'utilise Julia 1.2. C'est sans doute pour cela que j'ai cette erreur. Tu recommandes d'utiliser quelle version? La dernière, 1.4.1?

Ah top! J'ai vu effectivement que l'organisation du dossier avait changé. Je comptais updater tout à la main mais si c'est possible de le faire automatiquement c'est encore mieux :-)

**Comment by tlienart** [comment]
non malheureusement c'est pas complètement automatique mais c'est pas très difficile, t'as qu'a m'ajouter comme collaborateur sur le repo si t'as un souci et je t'aiderai. 

Un autre truc qui est nouveau c'est l'utilisation de "GitHub action" qui permet d'automatiser le déploiement & optimisation du site (en gros GitHub le fait pour toi) cf https://franklinjl.org/workflow/deploy/ (commentaires & aides a rendre les instructions plus claires bienvenus)

**Comment by guberger** [comment]
Thanks!

J'ai effectivement eu un peu de mal à passer à ce nouveau mode de "déploiement" mais ça venait surtout du fait que je ne maîtrisais rien en Git. Maintenant ça marche :-)

Peut-être un commentaire mineur: pour la partie "copy the contents of the private key" préciser qu'il faut aussi prendre les lignes "-----BEGIN OPENSSH PRIVATE KEY-----" and "-----END OPENSSH PRIVATE KEY-----".
